Enhances `dz_hyperbolictan`
COSIMA/regional-mom6 pull request #106
Opened 2024-02-16 15:34 UTC by navidcy

This PR simplifies `dz_hyperbolictan`. The parameter `ratio` is now defined as `thickness bottom layer / thickness top layer`. Thus there is no need for negative values of `ratio` that seemed only a matter of "convention". Now `ratio > 1` implies that the bottom layer is thicker, `ratio < 1` that the top is thicker and `ratio = 1` implies equally-spaced layers.

The PR also adds examples in the docstring that demonstrate the function's behavior.

2024-02-16 15:47 UTC, navidcy commented
@angus-g, do you know how can we run the doctest within the CI?

2024-02-17 06:16 UTC, navidcy commented
Note how now, with the change `npoints -> (npoints -1)` at

https://github.com/COSIMA/regional-mom6/blob/bcaafc36528337add215aca5ae32c8c52448e9bc/regional_mom6/regional_mom6.py#L460

the answer for `dz` is symmetric for `ratio` and `1 / ratio`. That's because now the value of `|tanh|` is the same for the top and bottom layer. (See the example in the docstring and compare with the values you'd get from `#main`).

2024-02-18 12:11 UTC, navidcy commented
Also, after inspection, I realise that this is not an iterative algorithm. It only does one iteration. The total depth is proportional to the thickness of the top layer so it suffices to start with any value for the top-layer thickness, compute the total depth that comes out, and then rescale the top-layer thickness so that the total depth is the `target_depth`.

2024-02-19 22:54 UTC, angus-g requested changes
I do think this is cleaner, and the doctests/unit tests are very welcome! A couple of style and functionality questions remain

2024-02-19 22:54 UTC, angus-g commented on regional_mom6/regional_mom6.py
> +    Generate a hyperbolic tangent thickness profile with ``nlayers`` vertical
```suggestion
    """Generate a hyperbolic tangent thickness profile with ``nlayers`` vertical
```

2024-02-19 22:54 UTC, angus-g commented on pyproject.toml
> +  "xarray<2024.02.0",
I guess we'll drop this now that #108 is merged

2024-02-19 22:54 UTC, angus-g commented on regional_mom6/regional_mom6.py
> +           50., 50., 50., 50., 50., 50., 50.])
For our docstring style, start as `Examples:` with rest of the section indented.

2024-02-19 22:54 UTC, angus-g commented on regional_mom6/regional_mom6.py
> +        )
```suggestion

    # rescaled top_layer_thickness so that total_depth == target_depth
    new_top_layer_thickness = top_layer_thickness * target_depth / total_depth
    return hyperbolictan_thickness_profile(
        nlayers, ratio, target_depth, new_top_layer_thickness
    )
```

2024-02-19 22:54 UTC, angus-g commented on tests/test_grid_generation.py
> +
Needed?

2024-02-19 22:54 UTC, angus-g commented on regional_mom6/regional_mom6.py
> +        )
I think this will end up very slightly adjusting the thickness profile in the demo notebooks:

### Previous
```
>>> rm.dz_hyperbolictan(76, 10, 4500)
array([ 11.06482427,  11.09757634,  11.13618909,  11.18170529,
        11.23535091,  11.29856638,  11.37304293,  11.46076439,
        11.56405553,  11.6856372 ,  11.82868925,  11.99692155,
        12.19465356,  12.42690229,  12.69947837,  13.0190887 ,
        13.39344342,  13.83136335,  14.34288203,  14.93933394,
        15.63341731,  16.43921607,  17.37216136,  18.44890824,
        19.68709976,  21.10498766,  22.72087959,  24.55238791,
        26.61546695,  28.92324663,  31.4847004 ,  34.30322463,
        37.37525029,  40.68904792,  44.22391328,  47.94991976,
        51.82838613,  55.81313011,  59.85246901,  63.89180791,
        67.87655189,  71.75501826,  75.48102473,  79.0158901 ,
        82.32968773,  85.40171338,  88.22023762,  90.78169138,
        93.08947107,  95.15255011,  96.98405842,  98.59995036,
       100.01783826, 101.25602978, 102.33277666, 103.26572195,
       104.07152071, 104.76560408, 105.36205598, 105.87357467,
       106.3114946 , 106.68584932, 107.00545965, 107.27803573,
       107.51028446, 107.70801646, 107.87624877, 108.01930082,
       108.14088249, 108.24417363, 108.33189509, 108.40637163,
       108.46958711, 108.52323273, 108.56874893, 108.60736168])
```

### New
```
>>> rm.hyperbolictan_thickness_profile(76, 10, 4500)
array([ 10.94614942,  10.97901927,  11.01785597,  11.06373649,
        11.11792973,  11.18192975,  11.25749437,  11.34668987,
        11.45194245,  11.57609732,  11.72248599,  11.89500236,
        12.09818794,  12.33732613,  12.61854487,  12.94892614,
        13.33661942,  13.79095471,  14.32254811,  14.94339026,
        15.66690424,  16.50795493,  17.48278757,  18.60886776,
        19.90459189,  21.38883417,  23.08029895,  24.9966542 ,
        27.15343855,  29.56276021,  32.23184339,  35.1615229 ,
        38.34483581,  41.76589845,  45.39927564,  49.21003201,
        53.15459472,  57.18245391,  61.23859872,  65.26645792,
        69.21102062,  73.02177699,  76.65515418,  80.07621682,
        83.25952973,  86.18920925,  88.85829242,  91.26761409,
        93.42439843,  95.34075368,  97.03221846,  98.51646074,
        99.81218487, 100.93826507, 101.9130977 , 102.7541484 ,
       103.47766237, 104.09850452, 104.63009792, 105.08443321,
       105.47212649, 105.80250776, 106.0837265 , 106.32286469,
       106.52605027, 106.69856664, 106.84495531, 106.96911018,
       107.07436276, 107.16355826, 107.23912288, 107.3031229 ,
       107.35731614, 107.40319666, 107.44203336, 107.47490321])
```

2024-02-19 22:54 UTC, angus-g commented on regional_mom6/regional_mom6.py
> +    )
Do we need this assertion? I imagine if it ever fails it would be extremely confusing to get a bare `AssertionError` at this point...

2024-02-19 22:54 UTC, angus-g commented on regional_mom6/regional_mom6.py
> +        )
I guess the old algorithm worked in a similar way, but is this guaranteed to always converge with the new tighter tolerance?

2024-02-20 02:59 UTC, navidcy commented on pyproject.toml
> +  "xarray<2024.02.0",
Yes. Merged main here so this is outdated now.

2024-02-20 04:20 UTC, navidcy commented on regional_mom6/regional_mom6.py
> +    Generate a hyperbolic tangent thickness profile with ``nlayers`` vertical
Is this the python style?

Or are you suggesting something like this for docstring format

```python
"""A short description of what the method does.

Following by an extended description of blah blah. Potentially with some examples.

Examples
=======

    >>> from this import that
    >>> that(foo)
    >>> 1.0
```

2024-02-20 04:22 UTC, angus-g commented on regional_mom6/regional_mom6.py
> +    Generate a hyperbolic tangent thickness profile with ``nlayers`` vertical
We pretty much follow the [Google style](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html), for your snippet:

```python
"""A short description of what the method does.

Following by an extended description of blah blah. Potentially with some examples.

Examples:
    >>> from this import that
    >>> that(foo)
    >>> 1.0

...
"""
```

2024-02-20 04:23 UTC, navidcy commented on regional_mom6/regional_mom6.py
> +           50., 50., 50., 50., 50., 50., 50.])
Deal!

2024-02-20 04:24 UTC, navidcy commented on tests/test_grid_generation.py
> +
I guess not, removing it!

2024-02-20 04:50 UTC, navidcy commented on regional_mom6/regional_mom6.py
> +    Generate a hyperbolic tangent thickness profile with ``nlayers`` vertical
Deal and done!

2024-02-20 04:51 UTC, navidcy commented on regional_mom6/regional_mom6.py
> +    )
removed it

2024-02-20 04:56 UTC, navidcy commented on regional_mom6/regional_mom6.py
> +        )
Yes. This change comes from the tanh profile change

```python
... tanh(2π * (np.arange(nlayers) / nlayers - 1/2))
```

to 

```python
... tanh(2π * (np.arange(nlayers) / (nlayers-1) - 1/2))
```

I changed this so that the tanh is symmetric at its end points. I was confused why `ratio` and `1 / ratio` were not giving me just the reverse profiles.

I'm pretty sure this asymmetry was introduced by accident from the sane human that coded this at first. This sane person was probably used to thinking in counting starting from 1, 2, 3, ...  (as we all learn when we are ~4 years old) and not starting from 0, 1, 2, ... like some snakes (pythons) do. 

(Yes, a slight critique here for the 0-counting system that give me trouble from time to time...)

(Btw, even in `#main`, providing a ratio between 0 and 1 does have (almost) the same effect as providing a negative ration. I say almost because the slight differences were coming from the asymmetry in the tanh profile.)

2024-02-20 05:02 UTC, navidcy commented on regional_mom6/regional_mom6.py
> +        )
Do we mind the change? What's the problem? We don't have any regression tests or test that try to reproduce results bit-wise. The changes are very subtle but help with the interpretability of the vertical profile generator.

I admit I had trouble understanding the function before. It was claiming that it was doing some iteration procedure, but it wasn't. Only 1 iteration was needed. And the initial height of the top layer wasn't relevant. Since the total depth is proportional to the top-layer thickness, whatever we started with the next iteration would rescale everything so that the sum was the `target_depth`. So the `min_dz` parameter wasn't relevant; I deleted it. And then I noticed that the `tolerance` wasn't relevant either since every time we could achieve machine precision tolerance. So I deleted that also! Then I realized that with the symmetric tanh profile we could have an analytic expression for the sum:

```python
layer_thicknesses = top_layer_thickness + 0.5 * (
    bottom_layer_thickness - top_layer_thickness
) * (1 + np.tanh(2 * np.pi * (np.arange(nlayers) / (nlayers - 1) - 1 / 2)))

np.sum(layer_thicknesses) == nlayers * (bottom_layer_thickness + top_layer_thickness) / 2
```

Thus, it only suffices to choose your `top_layer_thickness` appropriately and bam! you get the precise total depth from the first go! e847798 does that so it simplifies the method even more.

[Now you know all the journey I've been through in this PR ;) ]

2024-02-20 05:03 UTC, navidcy commented on regional_mom6/regional_mom6.py
> +        )
We can also tag a new release after this PR so that people who want to use the package with the exact previous values for the vertical profile can just use the previous tag.

2024-02-20 05:07 UTC, navidcy commented on regional_mom6/regional_mom6.py
> +        )
See my comment at https://github.com/COSIMA/regional-mom6/pull/106#discussion_r1495246385

Yes, the updated method is guaranteed to have a `sum(layer_thicknesses) == total_depth` up to machine precision! No iterations needed, no tolerances.

2024-02-20 05:09 UTC, angus-g commented on regional_mom6/regional_mom6.py
> +        )
> Do we mind the change?

I certainly don't, and I agree that the new behaviour is better. I just want to make sure that @ashjbarnes is aware of and on-board with it, so it doesn't break any of his work.

2024-02-20 05:10 UTC, angus-g commented on regional_mom6/regional_mom6.py
> +        )
Very elegant!

2024-02-20 05:10 UTC, navidcy commented on regional_mom6/regional_mom6.py
> +        )
this is now deleted; no recursion is needed!

2024-02-20 05:13 UTC, angus-g reviewed
Very nice, thanks for incorporating all the suggestions! Looks great from my end, but I'll hold off on giving approval to let @ashjbarnes have a look over and adapt to the (very small) changes to the profile, if necessary.

2024-02-20 05:14 UTC, navidcy commented on regional_mom6/regional_mom6.py
> +        )
We should definitely tag a new release and make a note of this in the "What changed" section, e.g., https://github.com/COSIMA/regional-mom6/releases/tag/v0.3.0

2024-02-20 05:16 UTC, angus-g commented on regional_mom6/regional_mom6.py
> +        )
Yep, agreed.

2024-02-20 05:43 UTC, navidcy commented
> Very nice, thanks for incorporating all the suggestions! Looks great from my end, but I'll hold off on giving approval to let @ashjbarnes have a look over and adapt to the (very small) changes to the profile, if necessary.

btw, what I am suggesting in #107 may also have some slight effect in vertical grid generation so perhaps it makes sense to settle #107 also before we tag a new release.

2024-02-20 05:47 UTC, ashjbarnes commented on regional_mom6/regional_mom6.py
> +        )
Sorry I've fallen a bit behind! I've been working on my tasman tides stuff the last couple of days. This looks good! And a new tag is a good idea. I'll keep using the old tag for my research runs to make sure I don't overwrite the vertical profile

2024-02-20 05:50 UTC, ashjbarnes approved these changes
This looks good to me. Passes the notebook and Angus has documented the minor changes to the default profile. I agree that a new tag is necessary with changelog so users know that their vertical profiles will change slightly

2024-02-20 05:51 UTC, navidcy commented on regional_mom6/regional_mom6.py
> +        )
No need to apologize!

2024-02-20 05:53 UTC, navidcy commented on regional_mom6/regional_mom6.py
> +        )
[btw, let's not resolve this comment so that is available for future reference to see what happened in this PR... I should have documented these in detail in a comment in the PR and not responding to a review comment but what to do, that's that now...  :)]

2024-02-21 07:41 UTC, navidcy commented
I'll try to incorporate the changes I suggest in #107 here to see how it alters the grid.

2024-02-21 08:13 UTC, navidcy commented
### `#main`

```python
>>> import regional_mom6 as rmom6
>>> expt = rmom6.experiment([143, 150], [-48, -38.95], ["2003-01-01 00:00:00", "2003-01-05 00:00:00"], 0.05, 75, 10, 4500, '.', '.', '.')
>>>
>>> expt.vgrid.zi
<xarray.DataArray 'zi' (zi: 76)>
array([  11.064824,   22.162401,   33.29859 ,   44.480295,   55.715646,
         67.014212,   78.387255,   89.84802 ,  101.412075,  113.097712,
        124.926402,  136.923323,  149.117977,  161.544879,  174.244357,
        187.263446,  200.656889,  214.488253,  228.831135,  243.770469,
        259.403886,  275.843102,  293.215264,  311.664172,  331.351272,
        352.456259,  375.177139,  399.729527,  426.344994,  455.26824 ,
        486.752941,  521.056165,  558.431416,  599.120464,  643.344377,
        691.294297,  743.122683,  798.935813,  858.788282,  922.68009 ,
        990.556642, 1062.31166 , 1137.792685, 1216.808575, 1299.138262,
       1384.539976, 1472.760213, 1563.541905, 1656.631376, 1751.783926,
       1848.767984, 1947.367935, 2047.385773, 2148.641803, 2250.974579,
       2354.240301, 2458.311822, 2563.077426, 2668.439482, 2774.313057,
       2880.624551, 2987.310401, 3094.31586 , 3201.593896, 3309.104181,
       3416.812197, 3524.688446, 3632.707747, 3740.848629, 3849.092803,
       3957.424698, 4065.83107 , 4174.300657, 4282.823889, 4391.392638,
       4500.      ])
Coordinates:
  * zi       (zi) float64 11.06 22.16 33.3 44.48 ... 4.283e+03 4.391e+03 4.5e+03
Attributes:
    units:    meters
>>>
>>> expt.vgrid.zl
<xarray.DataArray 'zl' (zl: 75)>
array([  16.597236,   27.711189,   38.866684,   50.071148,   61.333321,
         72.663495,   84.073777,   95.578402,  107.194103,  118.940531,
        130.840746,  142.921784,  155.215303,  167.75833 ,  180.594097,
        193.77299 ,  207.353611,  221.403934,  236.002576,  251.240136,
        267.220595,  284.06271 ,  301.901344,  320.888626,  341.194821,
        363.008753,  386.537579,  412.005721,  439.652727,  469.729864,
        502.495291,  538.207778,  577.119041,  619.464987,  665.456333,
        715.269256,  769.036876,  826.842378,  888.714516,  954.625994,
       1024.494918, 1098.189169, 1175.533197, 1256.31652 , 1340.303106,
       1427.240833, 1516.870332, 1608.932751, 1703.176111, 1799.360201,
       1897.260014, 1996.66791 , 2097.394692, 2199.269818, 2302.140968,
       2405.873162, 2510.347583, 2615.460228, 2721.12051 , 2827.249844,
       2933.780299, 3040.653325, 3147.81859 , 3255.232914, 3362.859323,
       3470.666205, 3578.62657 , 3686.717397, 3794.91907 , 3903.21489 ,
       4011.590645, 4120.034255, 4228.53545 , 4337.085506, 4445.677013])
Coordinates:
  * zl       (zl) float64 16.6 27.71 38.87 ... 4.229e+03 4.337e+03 4.446e+03
```

### This PR up to [c56b561](https://github.com/COSIMA/regional-mom6/pull/106/commits/c56b5616621a3fe02902b7e5c3b513b203a792de)

```python
>>> import regional_mom6 as rmom6
>>> expt = rmom6.experiment([143, 150], [-48, -38.95], ["2003-01-01 00:00:00", "2003-01-05 00:00:00"], 0.05, 75, 10, 4500, '.', '.', '.')
>>>
>>> expt.vgrid.zi
<xarray.DataArray 'zi' (zi: 76)>
array([  10.946149,   21.925169,   32.943025,   44.006761,   55.124691,
         66.306621,   77.564115,   88.910805,  100.362747,  111.938845,
        123.661331,  135.556333,  147.654521,  159.991847,  172.610392,
        185.559318,  198.895937,  212.686892,  227.00944 ,  241.952831,
        257.619735,  274.12769 ,  291.610477,  310.219345,  330.123937,
        351.512771,  374.59307 ,  399.589724,  426.743163,  456.305923,
        488.537766,  523.699289,  562.044125,  603.810024,  649.209299,
        698.419331,  751.573926,  808.75638 ,  869.994979,  935.261436,
       1004.472457, 1077.494234, 1154.149388, 1234.225605, 1317.485135,
       1403.674344, 1492.532637, 1583.800251, 1677.224649, 1772.565403,
       1869.597621, 1968.114082, 2067.926267, 2168.864532, 2270.77763 ,
       2373.531778, 2477.00944 , 2581.107945, 2685.738043, 2790.822476,
       2896.294602, 3002.09711 , 3108.180837, 3214.503701, 3321.029752,
       3427.728318, 3534.573274, 3641.542384, 3748.616747, 3855.780305,
       3963.019428, 4070.322551, 4177.679867, 4285.083063, 4392.525097,
       4500.      ])
Coordinates:
  * zi       (zi) float64 10.95 21.93 32.94 ... 4.285e+03 4.393e+03 4.5e+03
Attributes:
    units:    meters
>>>
>>> expt.vgrid.zl
<xarray.DataArray 'zl' (zl: 75)>
array([  16.419224,   27.414678,   38.451953,   49.538629,   60.683656,
         71.897585,   83.192862,   94.58415 ,  106.088719,  117.726893,
        129.522574,  141.503834,  153.703615,  166.16051 ,  178.919664,
        192.033781,  205.564247,  219.58237 ,  234.170714,  249.424526,
        265.453187,  282.381667,  300.351871,  319.523779,  340.076233,
        362.207188,  386.13322 ,  412.088051,  440.319882,  471.087303,
        504.653688,  541.280051,  581.216543,  624.692973,  671.908937,
        723.024347,  778.151223,  837.347607,  900.614278,  967.894665,
       1039.077967, 1114.005123, 1192.476965, 1274.263714, 1359.1149  ,
       1446.768949, 1536.961783, 1629.434058, 1723.936848, 1820.23578 ,
       1918.11373 , 2017.372312, 2117.832359, 2219.333664, 2321.734178,
       2424.908852, 2528.748271, 2633.157197, 2738.053092, 2843.364693,
       2949.030666, 3054.998364, 3161.2227  , 3267.665134, 3374.292777,
       3481.077602, 3587.995751, 3695.026939, 3802.153928, 3909.362084,
       4016.638989, 4123.974112, 4231.358525, 4338.784662, 4446.246113])
Coordinates:
  * zl       (zl) float64 16.42 27.41 38.45 ... 4.231e+03 4.339e+03 4.446e+03
```

### This PR after to [c56b561](https://github.com/COSIMA/regional-mom6/pull/106/commits/c56b5616621a3fe02902b7e5c3b513b203a792de)


```python
>>> import regional_mom6 as rmom6
>>> expt = rmom6.experiment([143, 150], [-48, -38.95], ["2003-01-01 00:00:00", "2003-01-05 00:00:00"], 0.05, 75, 10, 4500, '.', '.', '.')
>>>
>>> expt.vgrid.zi
<xarray.DataArray 'zi' (zi: 76)>
array([   0.      ,   11.092098,   22.217994,   33.383912,   44.597218,
         55.866623,   67.202428,   78.616806,   90.124136,  101.741393,
        113.488603,  125.389371,  137.471492,  149.767658,  162.316265,
        175.162339,  188.358571,  201.966485,  216.057726,  230.715453,
        246.035828,  262.129558,  279.123424,  297.161723,  316.407501,
        337.043423,  359.27209 ,  383.315584,  409.413988,  437.822647,
        468.807945,  502.641469,  539.592572,  579.919495,  623.859478,
        671.61847 ,  723.361277,  779.203058,  839.203058,  903.361277,
        971.61847 , 1043.859478, 1119.919495, 1199.592572, 1282.641469,
       1368.807945, 1457.822647, 1549.413988, 1643.315584, 1739.27209 ,
       1837.043423, 1936.407501, 2037.161723, 2139.123424, 2242.129558,
       2346.035828, 2450.715453, 2556.057726, 2661.966485, 2768.358571,
       2875.162339, 2982.316265, 3089.767658, 3197.471492, 3305.389371,
       3413.488603, 3521.741393, 3630.124136, 3738.616806, 3847.202428,
       3955.866623, 4064.597218, 4173.383912, 4282.217994, 4391.092098,
       4500.      ])
Coordinates:
  * zi       (zi) float64 0.0 11.09 22.22 33.38 ... 4.282e+03 4.391e+03 4.5e+03
Attributes:
    units:    meters
>>> 
>>> expt.vgrid.zl
<xarray.DataArray 'zl' (zl: 75)>
array([   5.546049,   16.655046,   27.800953,   38.990565,   50.23192 ,
         61.534526,   72.909617,   84.370471,   95.932764,  107.614998,
        119.438987,  131.430431,  143.619575,  156.041962,  168.739302,
        181.760455,  195.162528,  209.012106,  223.386589,  238.37564 ,
        254.082693,  270.626491,  288.142573,  306.784612,  326.725462,
        348.157757,  371.293837,  396.364786,  423.618317,  453.315296,
        485.724707,  521.11702 ,  559.756033,  601.889487,  647.738974,
        697.489873,  751.282167,  809.203058,  871.282167,  937.489873,
       1007.738974, 1081.889487, 1159.756033, 1241.11702 , 1325.724707,
       1413.315296, 1503.618317, 1596.364786, 1691.293837, 1788.157757,
       1886.725462, 1986.784612, 2088.142573, 2190.626491, 2294.082693,
       2398.37564 , 2503.38 [...]

2024-02-21 09:01 UTC, ashjbarnes commented
Yeah I think this is right. You set "minimum depth" so that mom treats anything shallower than this value to be land anyway. I expect that the free surface is handled by barotropic `eta` anyway so maybe it doesn't need to have the surface in `zi`. That's how my runs work anyway...

2024-02-21 09:04 UTC, navidcy commented
I see a `zl = 0` here for example...

https://mom6-analysiscookbook.readthedocs.io/en/latest/notebooks/vorticity.html

2024-02-21 09:10 UTC, navidcy commented
If the grid does not include the `zl = 0` then what's identified as SST or SSS or any surface field?

2024-02-22 04:06 UTC, ashjbarnes commented
Yeah good point.. you're right I think it's normal to have the first zi value to be 0! Oops, I thought these were only internal layers and the barotropic part of the model handled the surface. @angus-g do you think this would have profound implications for a model if the first zi was not at 0 and someone was trying to use if tor science? Asking for a friend... 

Let's alter the dz_hyperbolictan to force zi=0 at the top

2024-02-22 04:10 UTC, angus-g commented
If this is only for defining an ALE coordinate, the code for setting the coordinate resolution will just calculate dz from zi, i.e. `dz(:) = zi(1:nz) - zi(2:nz+1)`. I think you would've noticed other weirdness if somehow the free surface was uniformly depressed or whatever.

2024-02-22 06:45 UTC, navidcy commented
> Yeah good point.. you're right I think it's normal to have the first zi value to be 0! Oops, I thought these were only internal layers and the barotropic part of the model handled the surface. @angus-g do you think this would have profound implications for a model if the first zi was not at 0 and someone was trying to use if tor science? Asking for a friend...
> 
> Let's alter the dz_hyperbolictan to force zi=0 at the top

OK, just to clarify, the thickness profile generator `dz_hyperbolictan` is not the culprit here for not having `zl = 0`.
The culprit for that is

https://github.com/COSIMA/regional-mom6/blob/3e9844286db015e17940bbbacc2c35f7ddc82e23/regional_mom6/regional_mom6.py#L705-L713

which takes the thicknesses profile and then computes `zl = np.cumsum(thickness)`.

```python
>>> import numpy as np
>>> thicknesses = np.array([10, 20, 30])
>>> thicknesses
array([10, 20, 30])
>>> np.cumsum(thicknesses)
array([10, 30, 60])
```

We can change this behavior in this PR as suggested in #107.

In fact, I did change it (in [c56b561](https://github.com/COSIMA/regional-mom6/pull/106/commits/c56b5616621a3fe02902b7e5c3b513b203a792de)) to see how different things are and the vertical grid that comes out now is at https://github.com/COSIMA/regional-mom6/pull/106#issuecomment-1956101121. Compare the `#main` with `This PR after [c56b561](https://github.com/COSIMA/regional-mom6/pull/106/commits/c56b5616621a3fe02902b7e5c3b513b203a792de)`

2024-02-22 07:03 UTC, navidcy commented
Given the additional change in `_make_vgrid` I ask that you re-approve the PR before merging _or_ we can discuss how to proceed?

2024-02-22 10:46 UTC, navidcy commented
> Oops, I thought these were only internal layers and the barotropic part of the model handled the surface.

Just to clarify: The barotropic mode is not exactly "the surface". The barotropic mode is the depth-integrated flow. It's true that the evolution of the free surface is intimately connected with the barotropic mode because with $\eta$ the deviation of the free  surface from $z=0$, its linear evolution is

$$ \partial_t \eta(x, y, t) = w(x, y, z=0, t)$$

and for a hydrostatic model, we can diagnose $w$ from $u$ and $v$ using incompressibility:

$$ \partial_z w = - (\partial_x u + \partial_y v)$$

which when integrated from the bottom of the ocean (where $w=0$ to $z=0$ we get

$$ w(x, y, z=0, t) = - \int_{H(x, y)}^0 (\partial_x u + \partial_y v) \, \mathrm{d}z = - (\partial_x U + \partial_y V)$$

with $U$ and $V$ the depth-integrated $u$, $v$.

As we see, the free-surface involves information from the whole grid column, not just the surface.

2024-02-27 11:51 UTC, navidcy commented
@ashjbarnes are you happy if I merge this (that also includes the adding of `zi = 0` interface in the vertical grid)?

2024-03-12 22:05 UTC, ashjbarnes approved these changes
This is great Navid! Love the examples of how it works. Perhaps we should make a new tag release with this PR (along with others probably) since it will change the default vertical structures. Something to consider for #110

2024-03-13 04:39 UTC, navidcy commented
> Just to clarify: The barotropic mode is not exactly "the surface". The barotropic mode is the depth-integrated flow. It's true that the evolution of the free surface is intimately connected with the barotropic mode because with η the deviation of the free surface from z=0, its linear evolution is
> 
> ∂tη(x,y,t)=w(x,y,z=0,t)
> 
> and for a hydrostatic model, we can diagnose w from u and v using incompressibility:
> 
> ∂zw=−(∂xu+∂yv)
> 
> which when integrated from the bottom of the ocean (where w=0) up to z=0 we get
> 
> w(x,y,z=0,t)=−∫H(x,y)0(∂xu+∂yv)dz=−(∂xU+∂yV)
> 
> with U and V the depth-integrated u, v.
> 
> As we see, the free-surface involves information from the whole grid column, not just the surface.

(note: the above is true for fixed z-level coordinate btw)

2024-03-13 04:41 UTC, navidcy commented
I think @angus-g needs to re-approve

2024-03-13 04:42 UTC, navidcy commented
We'll definitely tag a new release after merging this or combine it with 1-2 other open PRs at the moment.

2024-03-13 04:57 UTC, angus-g approved these changes
I haven't looked at the changes but I'll switch to an approve to not hold you up!

2024-03-13 04:59 UTC, merged