Declutter example notebook
COSIMA/regional-mom6 pull request #83
Opened 2023-11-15 22:57 UTC by ashjbarnes

Here I've removed all descriptions of Gadi / NCI and almost all of Payu from the `reanalysis_forced` notebook, and deleted the model forced one. This will be migrated to cosima recipes

The old notebook cells for "setup era5" and "set up run directory" are now methods of the experiment class which further streamlines the notebook. The `using_payu` flag is included here to give users the option of a `config.yaml` file being generated for their experiment. It defaults to False. 

The default input directory has also been decluttered to make things generic and not Gadi-centric

Finally, to address the deprecation of the motu client (issue #79 ) I've removed this entirely and given users step by step instructions for using the GUI on Copernicus's website to download the required data.

2023-11-16 02:31 UTC, ashjbarnes commented
I'm going to update / fix the 'model forced' one then re-open this PR. Until we find a landing place for it I'll at least iron out some of the issues pointed out by Luwei

2023-11-16 04:21 UTC, ashjbarnes commented
I've re-added the ACCESS-OM2 example but made it clear in the markdown that it's intended for NCI users. This should be migrated elsewhere in COSIMA when we agree on the space

2023-11-17 03:25 UTC, ashjbarnes commented
Codecov is down because I've moved the `process era5` functionality to the package. A future PR that expands testing should address this rather than me making this PR longer. I've manually tested both notebooks and run the corresponding MOM6 experiments they produce

2023-11-21 05:25 UTC, angus-g requested changes

2023-11-21 05:25 UTC, angus-g commented on regional_mom6/regional_mom6.py
> +                ncpus = int(b[0]) * int(b[1]) - int(a)
An alternative could be to parse from the mask file directly (the filename could lie!)

```python
mask_tables = self.mom_input_dir.glob("mask_table.*")
for mask_table in mask_tables:
  with open(mask_table, "r") as f:
    masked_cpus = int(f.readline())
    x, y = (int(v) for v in f.readline().split(", "))
```

Otherwise, at least:
```suggestion
        for p in self.mom_input_dir.glob("mask_table.*"):
          mask_table, masked, layout = p.name.split(".")
          x, y = (int(v) for v in layout.split("x"))
          ncpus = (x * y) - masked
```

But, what if there are multiple mask tables? This (both mine and yours) will default to the lexicographically last. Also, the layout we're going to use is set by `FRE_tools()`, but the core count is determined here, at run time. If a mask file does exist, but `FRE_tools()` wasn't called, `self.layout` won't exist and you'll hit an error later on. If a different mask file exists to the one `FRE_tools()` creates, the core count and layout could be out of sync.

2023-11-21 05:25 UTC, angus-g commented on regional_mom6/regional_mom6.py
> +            raise ValueError
```python
for p in self.mom_input_dir.glob("mask_table.*"):
  ...
else:
  raise ValueError("No mask table found. Run FRE_tools() method first to generate one.")
```

2023-11-21 05:25 UTC, angus-g commented on regional_mom6/regional_mom6.py
> +        print("Number of CPUs required: ", ncpus)
Necessary?

2023-11-21 05:25 UTC, angus-g commented on regional_mom6/regional_mom6.py
> +        inputfile = open(f"{self.mom_run_dir}/MOM_input", "r")
Instead of all this string manipulation, you could modify `input.nml`, such as:

```nml
&MOM_input_nml
	output_directory = '.',
	input_filename = 'n',
	restart_input_dir = 'INPUT',
	restart_output_dir = 'RESTART',
	parameter_filename = 'MOM_input', 'MOM_override', 'MOM_layout'
/
```

Then write to `MOM_layout` directly.

```python
layout_params = {
  "MASKTABLE": mask_table,
  "LAYOUT": f"{self.layout[0]}, {self.layout[1]}",
  ...
}

with open(self.mom_input_dir / "MOM_layout", "w") as f:
  for param, val in layout_params.items():
    f.write(f"{param} = {val}\n")
```

2023-11-21 05:25 UTC, angus-g commented on regional_mom6/regional_mom6.py
> +            os.remove(f"{self.mom_run_dir}/config.yaml")
This doesn't really need to be *removed* in the non-payu case, does it?

2023-11-21 05:25 UTC, angus-g commented on regional_mom6/regional_mom6.py
> +            inputfile.close()
```python
with open(self.mom_run_dir / "config.yaml", "r") as f:
  payu_config = yaml.safe_load(f)

payu_config["ncpus"] = ncpus
payu_config["input"].append(self.mom_input_dir)

with open(self.mom_run_dir / "config.yaml", "w") as f:
  yaml.dump(payu_config)
```

2023-11-21 05:25 UTC, angus-g commented on regional_mom6/regional_mom6.py
> +            inputfile.close()
As with the yaml example, this should be done using Marshall's https://github.com/marshallward/f90nml

2023-11-21 05:25 UTC, angus-g commented on regional_mom6/regional_mom6.py
> +                    }
Because we're so deeply nested, Black kind of mangles this... Maybe split out the exponent, which reformats much more nicely (naming likely incorrect, too many magic constants for me to really know what's going on here):

```python
                dewpoint = 8.07131 - 1730.63 / (233.426 + rawdata["2d"]["d2m"] - 273.15)
                humidity = (
                    (0.622 / rawdata["sp"]["sp"]) * (10**dewpoint) * 101325 / 760
                )
```

2023-11-22 02:13 UTC, ashjbarnes commented on regional_mom6/regional_mom6.py
> +        inputfile = open(f"{self.mom_run_dir}/MOM_input", "r")
Oh yeah good idea! I know this code is a mess. I've been kind of developing as I go with my own research but haven't wanted to get too distracted on `regional-mom6` stuff so didn't do too much prettying-up for this PR

2023-11-22 02:14 UTC, ashjbarnes commented on regional_mom6/regional_mom6.py
> +            os.remove(f"{self.mom_run_dir}/config.yaml")
No, I was just trying to stick with the mantra of not being NCI-centric. Could be confusing to other users if they have a random config file that doesn't work for their system right?

2023-11-22 02:15 UTC, ashjbarnes commented on regional_mom6/regional_mom6.py
> +            inputfile.close()
Thanks! Would this repo then be included as a dependency?

2023-11-22 02:18 UTC, angus-g commented on regional_mom6/regional_mom6.py
> +            inputfile.close()
Yes, but it's a pretty low overhead dependency.

2023-11-22 02:24 UTC, angus-g commented on regional_mom6/regional_mom6.py
> +            os.remove(f"{self.mom_run_dir}/config.yaml")
I guess so, but it doesn't seem much more intrusive than all the other random files in the config directory.

2023-11-28 01:15 UTC, ashjbarnes commented on regional_mom6/regional_mom6.py
> +        )
I remember I did try using copytree here but it doesn't support the overwriting of files, so I went back to a subprocess. What's the proper way to copy and force overwrite? `distutils`?

2023-11-28 04:47 UTC, ashjbarnes commented on regional_mom6/regional_mom6.py
> +            raise ValueError
Resolved by just handling the 'no mask table' case properly

2023-11-28 04:50 UTC, angus-g commented on regional_mom6/regional_mom6.py
> +        )
You can do `shutil.copytree(src, dst, dirs_exist_ok=True)`

2023-11-28 04:52 UTC, ashjbarnes commented on regional_mom6/regional_mom6.py
> +                ncpus = int(b[0]) * int(b[1]) - int(a)
Yeah I'm not sure how to handle all the possibilities here. The point of this function is to really hold the hand of a new user. I'll get it to print a warning if there are multiple mask tables to prompt them to delete or move unwanted ones

2023-11-28 04:53 UTC, ashjbarnes commented on regional_mom6/regional_mom6.py
> +            os.remove(f"{self.mom_run_dir}/config.yaml")
Which files in the config  directory are you referring to? I've tried to tidy it up now to leave only the essentials. I think `config.yaml` would now be the only one that's not MOM specific

2023-11-28 04:56 UTC, angus-g commented on regional_mom6/regional_mom6.py
> +            os.remove(f"{self.mom_run_dir}/config.yaml")
I suppose I mean that the MOM-specific ones are pretty messy already, but I'm not fussed if you want to remove it.

2023-11-28 05:07 UTC, ashjbarnes commented on regional_mom6/regional_mom6.py
> +                    }
Done

2023-11-28 05:08 UTC, ashjbarnes commented on regional_mom6/regional_mom6.py
> +        )
Thanks Angus, I did this then went back because there were merge conflicts due to committing from here and my copy at the same time

2023-11-28 05:18 UTC, ashjbarnes commented on regional_mom6/regional_mom6.py
> +            inputfile.close()
Where do we include these new dependencies? 

I'm a bit confused with the structure. Which things go in "pyproject.toml" and which go in "environment-ci.yml"? Is esmpy confined to the environment folder because its a conda rather than pip install?

In that case I'll just add `pyyaml` to `environment-ci.yml`

2023-11-28 05:19 UTC, angus-g commented on regional_mom6/regional_mom6.py
> +            inputfile.close()
It should go in the pyproject.toml, because they're the Python dependencies, not the one specific to conda.

2023-11-28 05:22 UTC, ashjbarnes commented on regional_mom6/regional_mom6.py
> +            inputfile.close()
Similar to comment above, does this just go in "dependencies" field of the pyproject.toml file?

2023-11-28 05:23 UTC, angus-g commented on regional_mom6/regional_mom6.py
> +            inputfile.close()
Yes.

2023-11-28 05:24 UTC, angus-g commented on regional_mom6/regional_mom6.py
> +            inputfile.close()
Also, I think it should be called `PyYAML` (although I don't know if capitalisation matters for packages...)

2023-11-28 23:34 UTC, ashjbarnes commented on regional_mom6/regional_mom6.py
> +        inputfile = open(f"{self.mom_run_dir}/MOM_input", "r")
This would break if the `MOM_input` file already had parameter stuff right? Because otherwise we'd need to do an override?

Say if user would BYO a run directory and then opt to modify it, they'd likely already have layout parameters and then you'd get duplicates. Maybe it's just easier to modify `MOM_input` or override the layout?

2023-11-28 23:35 UTC, ashjbarnes commented on regional_mom6/regional_mom6.py
> +            os.remove(f"{self.mom_run_dir}/config.yaml")
Feedback from @navidcy was to remove nci specific things. I don't mind either except that it's probably easier for others to understand what's going on if there aren't unfamiliar non-MOM files floating around

2023-11-29 02:31 UTC, ashjbarnes commented on regional_mom6/regional_mom6.py
> +            inputfile.close()
pyyaml mangles the manipulation of `config.yaml` for some reason. pyyaml fails to read in the multiple input lines (just gets the first one) and then re-writes the yaml file in alphabetical order.

I don't have time to fiddle with this so I'm going to revert back to the string manipulations

2023-11-29 02:56 UTC, ashjbarnes commented on regional_mom6/regional_mom6.py
> +            inputfile.close()
Latest commit reverts to string manipulations and has been tested on example notebooks.

2023-11-29 02:58 UTC, ashjbarnes commented on regional_mom6/regional_mom6.py
> +        inputfile = open(f"{self.mom_run_dir}/MOM_input", "r")
I've stuck to just modifying the `MOM_input` file since I think this is ultimately more user friendly, and then we don't have to worry about existing / not existing layout parameters in `MOM_input`

2023-11-29 03:03 UTC, ashjbarnes commented on regional_mom6/regional_mom6.py
> +            inputfile.close()
Thanks Micael but again this isn't a priority for now. I've already given it some time, and it didn't work. If we want to update / tidy the existing code then that can be a separate PR.

2023-11-29 03:11 UTC, ashjbarnes commented on regional_mom6/regional_mom6.py
> +            inputfile.close()
@micaeljtoliveira Thanks, yes would be good to do one day! Sorry for the short response - I feel sometimes that there are a million things to do with this repo and I'm always tempted to keep working away instead of other priorities with my PhD. Hence I'm trying to be careful about keeping PRs on task and not getting too sidetracked

2023-12-05 23:28 UTC, ashjbarnes commented
Are we happy to tidy up string manipulations in a separate PR later? For now things are working even if a bit ugly for the `yaml` editing

2023-12-06 03:15 UTC, angus-g commented
Apologies, fixed. I had no clue you were working live off a PR branch, I would strongly advise against doing that.

2023-12-06 03:17 UTC, ashjbarnes commented
If not, then from a github workflow perspective what's the best way for me to keep working for the moment? I'm losing a lot of time trying to juggle the codebase when this PR is unresolved and I'm already working on the next one (and need it for my day-to-day research). It was becoming too much admin to continually merge changes from this branch into the `withtides` branch, especially when merge conflicts cropped up. 

I then manually made a new branch forked from `declutter_notebook` to build off but then had to troubleshoot why things weren't working. Perhaps there's a better way of doing things that I'm not aware of?

2023-12-13 10:53 UTC, navidcy commented
I haven't followed any discussion here. @ashjbarnes, @angus-g is this PR under control? If you need help ping me.

2023-12-14 07:48 UTC, ashjbarnes commented
Latest commit implements what we talked about today @angus-g . Notebook has been tested but I'll go back and modify notebooks to add some more documentation - that'll be the last planned commit from me unless something else comes up / breaks!

Thanks @navidcy ! Almost finished :)

2024-01-16 01:38 UTC, ashjbarnes commented on regional_mom6/regional_mom6.py
> +        print("Number of CPUs required: ", ncpus)
This is useful for non-payu users as they'll need to enter in the number of cpus into whatever system they're using

2024-01-16 03:46 UTC, angus-g approved these changes

2024-01-16 06:19 UTC, navidcy submitted a review, later dismissed

2024-01-16 06:19 UTC, navidcy commented on regional_mom6/regional_mom6.py
> +        if varnames["time"] in ic_raw
this can't be right... python can't even parse it

2024-01-16 07:57 UTC, ashjbarnes commented on regional_mom6/regional_mom6.py
> +        if varnames["time"] in ic_raw
Don't worry about this, I was testing this code one last time after my patches and bugfixing. I was just using github to sync my local changes to gadi so I could run the example notebooks. I'll finish testing, then commit the last fixes and then merge

2024-01-16 08:17 UTC, navidcy commented
tip: 
before pushing you should format with black otherwise tests don't run... and tests that fail might hint you about something wrong that is happening. If you postpone formatting black (and thus running the tests) you may not see a bug you introduced until way after you've put substantial effort in refactoring something that you may need to undo.

2024-01-17 09:51 UTC, navidcy commented on regional_mom6/regional_mom6.py
> +import yaml
did we add these packages as dependencies?

2024-01-17 09:53 UTC, navidcy commented on regional_mom6/regional_mom6.py
> +import yaml
I see only 

```python
  "PyYAML>=6.0.1",
  "f90nml>=1.4.1",
```

what about `os` and `shutil`?

2024-01-17 10:47 UTC, angus-g commented on regional_mom6/regional_mom6.py
> +import yaml
They're both part of Python itself.

2024-01-18 01:01 UTC, ashjbarnes commented
Everything tested and working with latest executable. Ready to merge

2024-01-18 01:01 UTC, merged