Update README.md to specify MOM6 version requirements and configuration
COSIMA/regional-mom6 pull request #90
Opened 2024-01-18 06:29 UTC by ashjbarnes

closes #87

2024-01-18 06:31 UTC, ashjbarnes commented
Just thought I'd get your opinion as to whether this approach makes sense. The package itself doesn't care about the version used (afaik) but the demo notebooks do

2024-01-18 07:08 UTC, navidcy commented on README.md
> +The current release of this package assumes the latest source code of all components needed to run MOM6 as of January 2024. Note that GFDL's `MOM6_examples` repository uses older versions of the Flex
```suggestion
The current release of this package assumes the latest source code of all components needed to run MOM6 as of January 2024. Note that GFDL's `MOM6_examples` repository uses older versions of the Flexible Modelling System (FMS), coupler, SIS2 and other components, so using the source code from here will *not* necessarily work. [This repository](https://github.com/ashjbarnes/setup-mom6-nci) contains scripts for compiling MOM6, and includes a folder `src` containing submodules linked to the correct versions known to work with this package and its demos.
```

I'm wondering: instead of writing comments like this that have the danger of getting outdated can't we just enforce dependency requirements and then everything is clear?

2024-01-19 05:56 UTC, navidcy commented
OK, fair point!

Then let's be a bit more specific.

- Let's avoid "as of January 2024". The commit come with a timestamp.
- Let's not say which versions won't work, e.g., "the source code from here will *not* necessarily work."
- Let's just say which versions work. E.g., "`regional-mom6 requires you to build mom6 executable from commit XXX"

2024-01-19 05:57 UTC, navidcy requested changes
OK, fair point!

Then let's be a bit more specific.

- Let's avoid "as of January 2024". These statements become outdated... The commit anyway comes with a timestamp so everyone knows when the latest README was written.
- Let's not say which versions won't work, e.g., "the source code from here will not necessarily work."
- Let's just say which versions work. E.g., "`regional-mom6 requires you to build mom6 executable from commit XXX"

2024-01-19 06:01 UTC, navidcy commented
Also regarding:

> While the underlying package should work for coupled or ocean only configurations, the premade files for the demos are written for a coupled MOM6-SIS2 configuration.

Do we know for sure that it should work for coupled or ocean only configurations? Have we ever tested it? Let's not hypothesise if not. It's cleaner if we say

> All demos and tests were conducted for a coupled MOM6-SIS2 configuration. In principle, `regional-mom6` could also work for coupled or ocean-only MOM6 configurations, but we have not tested it.

Also, what is the difference of "coupled" and "coupled MOM6-SIS2"?

2024-01-22 00:50 UTC, ashjbarnes commented
>     * Let's just say which versions work. E.g., "`regional-mom6 requires you to build mom6 executable from commit XXX"

I'd rather not do this as it'll clutter up the readme a lot given there are many required packages. The link to my repo and the `src` directory there should be sufficient

2024-01-22 00:53 UTC, ashjbarnes commented
>     * Let's avoid "as of January 2024". These statements become outdated... The commit anyway comes with a timestamp so everyone knows when the latest README was written.

Yes but if we update another part of the readme then the timestamp will change and readers shouldn't then assume that the 'latest' source code refers to that timestamp. I think this way is clearest for now, especially with the link to the `src` directory of commits.

2024-01-22 06:05 UTC, navidcy commented
> > ```
> > * Let's just say which versions work. E.g., "`regional-mom6 requires you to build mom6 executable from commit XXX"
> > ```
> 
> I'd rather not do this as it'll clutter up the readme a lot given there are many required packages. The link to my repo and the `src` directory there should be sufficient

I only meant to write explicitly the versions of dependencies that cannot be properly added as package dependencies.

2024-01-22 06:16 UTC, navidcy approved these changes
OK, I only now realized that your repo listed all the commits used to compile MOM6 and its subcomponents.

I rephrased a bit. I think it's good now! It provides the info needed!

2024-01-22 06:16 UTC, navidcy commented on README.md
> +The current release of this package assumes the latest source code of all components needed to run MOM6 as of January 2024. Note that GFDL's `MOM6_examples` repository uses older versions of the Flex
```suggestion
The current release of this package assumes the latest source code of all components needed to run MOM6 as of January 2024. The [`setup-mom6-nci`](https://github.com/ashjbarnes/setup-mom6-nci) repository contains scripts for compiling MOM6. The directory [`src`](https://github.com/ashjbarnes/setup-mom6-nci/tree/setup-mom6/src) of the above-mentioned repository lists the particular commits that were used to compile MOM6 and its submodules for this package.

Note that the commits used for MOM6 submodules (e.g., Flexible Modelling System (FMS), coupler, SIS2) are _not_ necessarily those used by the GFDL's [`MOM6_examples`](https://github.com/NOAA-GFDL/MOM6-examples) repository.
```

2024-01-22 22:19 UTC, merged